#!/bin/bash

#DEBHELPER#

# preinst script for lightdm-modified-init

#set -e

case "$1" in
  install|upgrade) dpkg-divert --quiet                                               \
                               --add                                                 \
                               --package lightdm-modified-init            \
                               --rename                              \
                               --divert /etc/init.d/lightdm.dpkg-distrib \
                               /etc/init.d/lightdm
                               
                               ##part of dpkg-divert removal
                               	if [ ! -e /usr/share/xsessions/lightdm-xsession.desktop.dpkg-distrib ]; then
                               		if [ -e /usr/share/xsessions/lightdm-xsession.desktop ]; then
                               			cp /usr/share/xsessions/lightdm-xsession.desktop /usr/share/xsessions/lightdm-xsession.desktop.dpkg-distrib
                               		fi
                               	fi
                               
                   ;;

                *) :
                   ;;
esac 

exit 0
